name: Run on Fly
on: [push]
jobs:
  deploy:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: "flyctl ssh console --command 'sh ./run-e2e.sh'"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
